/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CofounderIndexRouteImport } from './routes/cofounder/index'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze/index'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as PaymentRedeemRouteImport } from './routes/_payment/redeem'
import { Route as PaymentPricingRouteImport } from './routes/_payment/pricing'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRequestResetPasswordRouteImport } from './routes/_auth/request-reset-password'
import { Route as AuthAuthenticateRouteImport } from './routes/_auth/authenticate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PaymentBillingPackIdRouteImport } from './routes/_payment/billing/$packId'
import { Route as ApiStreamJobIdRouteRouteImport } from './routes/api/stream/$jobId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CofounderIndexRoute = CofounderIndexRouteImport.update({
  id: '/cofounder/',
  path: '/cofounder/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRedeemRoute = PaymentRedeemRouteImport.update({
  id: '/_payment/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPricingRoute = PaymentPricingRouteImport.update({
  id: '/_payment/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestResetPasswordRoute =
  AuthRequestResetPasswordRouteImport.update({
    id: '/_auth/request-reset-password',
    path: '/request-reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthenticateRoute = AuthAuthenticateRouteImport.update({
  id: '/_auth/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentBillingPackIdRoute = PaymentBillingPackIdRouteImport.update({
  id: '/_payment/billing/$packId',
  path: '/billing/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamJobIdRouteRoute = ApiStreamJobIdRouteRouteImport.update({
  id: '/api/stream/$jobId',
  path: '/api/stream/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticate': typeof AuthAuthenticateRoute
  '/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/pricing': typeof PaymentPricingRoute
  '/redeem': typeof PaymentRedeemRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/cofounder/': typeof CofounderIndexRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRouteRoute
  '/billing/$packId': typeof PaymentBillingPackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticate': typeof AuthAuthenticateRoute
  '/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/pricing': typeof PaymentPricingRoute
  '/redeem': typeof PaymentRedeemRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/analyze': typeof AnalyzeIndexRoute
  '/cofounder': typeof CofounderIndexRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRouteRoute
  '/billing/$packId': typeof PaymentBillingPackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/authenticate': typeof AuthAuthenticateRoute
  '/_auth/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_payment/pricing': typeof PaymentPricingRoute
  '/_payment/redeem': typeof PaymentRedeemRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/cofounder/': typeof CofounderIndexRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRouteRoute
  '/_payment/billing/$packId': typeof PaymentBillingPackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticate'
    | '/request-reset-password'
    | '/reset-password'
    | '/pricing'
    | '/redeem'
    | '/settings/credits'
    | '/analyze/'
    | '/cofounder/'
    | '/api/stream/$jobId'
    | '/billing/$packId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticate'
    | '/request-reset-password'
    | '/reset-password'
    | '/pricing'
    | '/redeem'
    | '/settings/credits'
    | '/analyze'
    | '/cofounder'
    | '/api/stream/$jobId'
    | '/billing/$packId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth/authenticate'
    | '/_auth/request-reset-password'
    | '/_auth/reset-password'
    | '/_payment/pricing'
    | '/_payment/redeem'
    | '/settings/credits'
    | '/analyze/'
    | '/cofounder/'
    | '/api/stream/$jobId'
    | '/_payment/billing/$packId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAuthenticateRoute: typeof AuthAuthenticateRoute
  AuthRequestResetPasswordRoute: typeof AuthRequestResetPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  PaymentPricingRoute: typeof PaymentPricingRoute
  PaymentRedeemRoute: typeof PaymentRedeemRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
  CofounderIndexRoute: typeof CofounderIndexRoute
  ApiStreamJobIdRouteRoute: typeof ApiStreamJobIdRouteRoute
  PaymentBillingPackIdRoute: typeof PaymentBillingPackIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofounder/': {
      id: '/cofounder/'
      path: '/cofounder'
      fullPath: '/cofounder/'
      preLoaderRoute: typeof CofounderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/settings/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payment/redeem': {
      id: '/_payment/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof PaymentRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payment/pricing': {
      id: '/_payment/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PaymentPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/request-reset-password': {
      id: '/_auth/request-reset-password'
      path: '/request-reset-password'
      fullPath: '/request-reset-password'
      preLoaderRoute: typeof AuthRequestResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/authenticate': {
      id: '/_auth/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthAuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payment/billing/$packId': {
      id: '/_payment/billing/$packId'
      path: '/billing/$packId'
      fullPath: '/billing/$packId'
      preLoaderRoute: typeof PaymentBillingPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$jobId': {
      id: '/api/stream/$jobId'
      path: '/api/stream/$jobId'
      fullPath: '/api/stream/$jobId'
      preLoaderRoute: typeof ApiStreamJobIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAuthenticateRoute: AuthAuthenticateRoute,
  AuthRequestResetPasswordRoute: AuthRequestResetPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  PaymentPricingRoute: PaymentPricingRoute,
  PaymentRedeemRoute: PaymentRedeemRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
  CofounderIndexRoute: CofounderIndexRoute,
  ApiStreamJobIdRouteRoute: ApiStreamJobIdRouteRoute,
  PaymentBillingPackIdRoute: PaymentBillingPackIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
