/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CofounderIndexRouteImport } from './routes/cofounder/index'
import { Route as AuthenticateIndexRouteImport } from './routes/authenticate/index'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStreamJobIdRouteRouteImport } from './routes/api/stream/$jobId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CofounderIndexRoute = CofounderIndexRouteImport.update({
  id: '/cofounder/',
  path: '/cofounder/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateIndexRoute = AuthenticateIndexRouteImport.update({
  id: '/authenticate/',
  path: '/authenticate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamJobIdRouteRoute = ApiStreamJobIdRouteRouteImport.update({
  id: '/api/stream/$jobId',
  path: '/api/stream/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/authenticate/': typeof AuthenticateIndexRoute
  '/cofounder/': typeof CofounderIndexRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeIndexRoute
  '/authenticate': typeof AuthenticateIndexRoute
  '/cofounder': typeof CofounderIndexRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/authenticate/': typeof AuthenticateIndexRoute
  '/cofounder/': typeof CofounderIndexRoute
  '/api/stream/$jobId': typeof ApiStreamJobIdRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze/'
    | '/authenticate/'
    | '/cofounder/'
    | '/api/stream/$jobId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/authenticate'
    | '/cofounder'
    | '/api/stream/$jobId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/analyze/'
    | '/authenticate/'
    | '/cofounder/'
    | '/api/stream/$jobId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
  AuthenticateIndexRoute: typeof AuthenticateIndexRoute
  CofounderIndexRoute: typeof CofounderIndexRoute
  ApiStreamJobIdRouteRoute: typeof ApiStreamJobIdRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofounder/': {
      id: '/cofounder/'
      path: '/cofounder'
      fullPath: '/cofounder/'
      preLoaderRoute: typeof CofounderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticate/': {
      id: '/authenticate/'
      path: '/authenticate'
      fullPath: '/authenticate/'
      preLoaderRoute: typeof AuthenticateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$jobId': {
      id: '/api/stream/$jobId'
      path: '/api/stream/$jobId'
      fullPath: '/api/stream/$jobId'
      preLoaderRoute: typeof ApiStreamJobIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
  AuthenticateIndexRoute: AuthenticateIndexRoute,
  CofounderIndexRoute: CofounderIndexRoute,
  ApiStreamJobIdRouteRoute: ApiStreamJobIdRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
